In [28]:
import pandas as pd
import numpy as np

In [29]:
# Creating raw dataset
data = {'property_id':[1,2,3,4,5], 
'price':[250000,300000,150000,400000,350000],
'size_sqft':[1500,2000,1200,2500,1800],
'date_listed':['2023-01-15','2023-02-20','2023-03-10','2023-04-05','2023-05-01'],
'year_built':[1990,2005,1980,2010,2000],
'property_type':['Apartment','Villa','Apartment','Villa','Independent House'],
'location':['Vizag','Hyderabad','Vizag','Bangalore','Chennai']
}

In [30]:
df = pd.DataFrame(data)
df

,property_id,price,size_sqft,date_listed,year_built,property_type,location
0,1,250000,1500,2023-01-15,1990,Apartment,Vizag
1,2,300000,2000,2023-02-20,2005,Villa,Hyderabad
2,3,150000,1200,2023-03-10,1980,Apartment,Vizag
3,4,400000,2500,2023-04-05,2010,Villa,Bangalore
4,5,350000,1800,2023-05-01,2000,Independent House,Chennai

In [31]:
# Price per sqft
df['price_per_sqft'] = df['price'] / df['size_sqft']
df['price_per_sqft'] = df['price_per_sqft'].round(2)
df

,property_id,price,size_sqft,date_listed,year_built,property_type,location,price_per_sqft
0,1,250000,1500,2023-01-15,1990,Apartment,Vizag,166.67
1,2,300000,2000,2023-02-20,2005,Villa,Hyderabad,150.00
2,3,150000,1200,2023-03-10,1980,Apartment,Vizag,125.00
3,4,400000,2500,2023-04-05,2010,Villa,Bangalore,160.00
4,5,350000,1800,2023-05-01,2000,Independent House,Chennai,194.44

In [32]:
#data transformation
df['date_listed'] = pd.to_datetime(df['date_listed'])
df

,property_id,price,size_sqft,date_listed,year_built,property_type,location,price_per_sqft
0,1,250000,1500,2023-01-15,1990,Apartment,Vizag,166.67
1,2,300000,2000,2023-02-20,2005,Villa,Hyderabad,150.00
2,3,150000,1200,2023-03-10,1980,Apartment,Vizag,125.00
3,4,400000,2500,2023-04-05,2010,Villa,Bangalore,160.00
4,5,350000,1800,2023-05-01,2000,Independent House,Chennai,194.44

In [33]:
df['month'] = df['date_listed'].dt.month   # Extracting month from date_listed
df

,property_id,price,size_sqft,date_listed,year_built,property_type,location,price_per_sqft,month
0,1,250000,1500,2023-01-15,1990,Apartment,Vizag,166.67,1
1,2,300000,2000,2023-02-20,2005,Villa,Hyderabad,150.00,2
2,3,150000,1200,2023-03-10,1980,Apartment,Vizag,125.00,3
3,4,400000,2500,2023-04-05,2010,Villa,Bangalore,160.00,4
4,5,350000,1800,2023-05-01,2000,Independent House,Chennai,194.44,5

In [34]:
df['listing_year'] = df['date_listed'].dt.year # Extracting year from date_listed
df

,property_id,price,size_sqft,date_listed,year_built,property_type,location,price_per_sqft,month,listing_year
0,1,250000,1500,2023-01-15,1990,Apartment,Vizag,166.67,1,2023
1,2,300000,2000,2023-02-20,2005,Villa,Hyderabad,150.00,2,2023
2,3,150000,1200,2023-03-10,1980,Apartment,Vizag,125.00,3,2023
3,4,400000,2500,2023-04-05,2010,Villa,Bangalore,160.00,4,2023
4,5,350000,1800,2023-05-01,2000,Independent House,Chennai,194.44,5,2023

In [35]:
from sklearn.preprocessing import MinMaxScaler #normalization
scaler = MinMaxScaler()
df['normalized_price'] = scaler.fit_transform(df[['price']])
df

,property_id,price,size_sqft,date_listed,year_built,property_type,location,price_per_sqft,month,listing_year,normalized_price
0,1,250000,1500,2023-01-15,1990,Apartment,Vizag,166.67,1,2023,0.4
1,2,300000,2000,2023-02-20,2005,Villa,Hyderabad,150.00,2,2023,0.6
2,3,150000,1200,2023-03-10,1980,Apartment,Vizag,125.00,3,2023,0.0
3,4,400000,2500,2023-04-05,2010,Villa,Bangalore,160.00,4,2023,1.0
4,5,350000,1800,2023-05-01,2000,Independent House,Chennai,194.44,5,2023,0.8

In [36]:
from sklearn.preprocessing import StandardScaler #standardization
scaler = StandardScaler()
df['standard_size'] = scaler.fit_transform(df[['size_sqft']])
df

,property_id,price,size_sqft,date_listed,year_built,property_type,location,price_per_sqft,month,listing_year,normalized_price,standard_size
0,1,250000,1500,2023-01-15,1990,Apartment,Vizag,166.67,1,2023,0.4,-0.677631
1,2,300000,2000,2023-02-20,2005,Villa,Hyderabad,150.00,2,2023,0.6,0.451754
2,3,150000,1200,2023-03-10,1980,Apartment,Vizag,125.00,3,2023,0.0,-1.355262
3,4,400000,2500,2023-04-05,2010,Villa,Bangalore,160.00,4,2023,1.0,1.581139
4,5,350000,1800,2023-05-01,2000,Independent House,Chennai,194.44,5,2023,0.8,0.000000

In [37]:
df = pd.get_dummies(df, columns=['property_type']) # One-hot encoding for property_type
df

,property_id,price,size_sqft,date_listed,year_built,location,price_per_sqft,month,listing_year,normalized_price,standard_size,property_type_Apartment,property_type_Independent House,property_type_Villa
0,1,250000,1500,2023-01-15,1990,Vizag,166.67,1,2023,0.4,-0.677631,True,False,False
1,2,300000,2000,2023-02-20,2005,Hyderabad,150.00,2,2023,0.6,0.451754,False,False,True
2,3,150000,1200,2023-03-10,1980,Vizag,125.00,3,2023,0.0,-1.355262,True,False,False
3,4,400000,2500,2023-04-05,2010,Bangalore,160.00,4,2023,1.0,1.581139,False,False,True
4,5,350000,1800,2023-05-01,2000,Chennai,194.44,5,2023,0.8,0.000000,False,True,False

In [38]:
from sklearn.preprocessing import LabelEncoder # Label encoding for location
le = LabelEncoder()
df['location_encoded'] = le.fit_transform(df['location'])
df

,property_id,price,size_sqft,date_listed,year_built,location,price_per_sqft,month,listing_year,normalized_price,standard_size,property_type_Apartment,property_type_Independent House,property_type_Villa,location_encoded
0,1,250000,1500,2023-01-15,1990,Vizag,166.67,1,2023,0.4,-0.677631,True,False,False,3
1,2,300000,2000,2023-02-20,2005,Hyderabad,150.00,2,2023,0.6,0.451754,False,False,True,2
2,3,150000,1200,2023-03-10,1980,Vizag,125.00,3,2023,0.0,-1.355262,True,False,False,3
3,4,400000,2500,2023-04-05,2010,Bangalore,160.00,4,2023,1.0,1.581139,False,False,True,0
4,5,350000,1800,2023-05-01,2000,Chennai,194.44,5,2023,0.8,0.000000,False,True,False,1

In [39]:
Q1 = df['price'].quantile(0.25) #outlier detection using IQR
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1
outliers = df[ (df['price'] < (Q1 - 1.5 * IQR)) | (df['price'] > (Q3 + 1.5 * IQR))
]
outliers

Empty DataFrame
Columns: [property_id, price, size_sqft, date_listed, year_built, location, price_per_sqft, month, listing_year, normalized_price, standard_size, property_type_Apartment, property_type_Independent House, property_type_Villa, location_encoded]
Index: []

In [40]:
df

,property_id,price,size_sqft,date_listed,year_built,location,price_per_sqft,month,listing_year,normalized_price,standard_size,property_type_Apartment,property_type_Independent House,property_type_Villa,location_encoded
0,1,250000,1500,2023-01-15,1990,Vizag,166.67,1,2023,0.4,-0.677631,True,False,False,3
1,2,300000,2000,2023-02-20,2005,Hyderabad,150.00,2,2023,0.6,0.451754,False,False,True,2
2,3,150000,1200,2023-03-10,1980,Vizag,125.00,3,2023,0.0,-1.355262,True,False,False,3
3,4,400000,2500,2023-04-05,2010,Bangalore,160.00,4,2023,1.0,1.581139,False,False,True,0
4,5,350000,1800,2023-05-01,2000,Chennai,194.44,5,2023,0.8,0.000000,False,True,False,1